### ISSUE TITLE
PA-100k Question!

### ISSUE THREAD

**Issue by haydenth** [xh-liu/HydraPlus-Net#1]
Hello! I love this research! Question: is the PA-100K derived from another pedestrian detection dataset? Or is it collected and generated independently?

**Comment by xh-liu** [comment]
Hi! Thank you for your attention. This dataset is collected and generated independently, rather than from another dataset.

**Comment by haydenth** [comment]
Cool - thanks. Would be helpful if you could publish the full images too! :) This is great research, thanks for sharing your data.

**Comment by hongsamvo** [comment]
Thank you for your contribution, I would like to ask about the attribute list of PA100K dataset
