### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zvif** [xh-liu/HydraPlus-Net#16]
Hi,
Can you add a specific license (for the dataset)? 
I suggest the CC-BY 4.0 license "Creative Commons — Attribution 4.0 International — CC BY 4.0"

Thanks
Zvi

**Comment by xh-liu** [comment]
Hi,

Thank you for suggesting. I will add CC-BY 4.0 license to the dataset.

**Comment by zvif** [comment]
Great!
