### ISSUE TITLE
Where to download the dataset pa-100k?

### ISSUE THREAD

**Issue by xhzcyc** [xh-liu/HydraPlus-Net#4]
Hello, 
Could you share your dataset ?
Thanks

**Comment by xh-liu** [comment]
Hi,

The dataset can be downloaded here:

https://drive.google.com/drive/folders/0B5_Ra3JsEOyOUlhKM0VPZ1ZWR2M

Thanks!

**Comment by Hucley** [comment]
Could you share your dataset with a inks available in China？
